### ISSUE TITLE
Lexical error while using RYandexTranlate package

### ISSUE THREAD

**Issue by Nikhil5harma** [mukul13/RYandexTranslate#2]
I have generated an api_key as suggested in the document. I am trying to translate text from one language to other using the translate inbuilt function in the package. However if I use space in the text, R throws an error: 

Error: lexical error: invalid char in json text.
                                       <html>  <head><title>400 Bad Re
                     (right here) ------^

I am using the following syntax:
translate( my_api_key, text="Hi, how are you" ,lang = "en-de")

Could you please suggest me a solution. 

Thanks,
Nikhil

**Comment by jacquespeeters** [comment]
Same here problem here 
``translate(api_key,text="hello ",lang="en-fr"  )``

When i check the function's code
```
function (api_key, text = "", lang = "") 
{
  url = "https://translate.yandex.net/api/v1.5/tr.json/translate?"
  url = paste(url, "key=", api_key, sep = "")
  if (text != "") {
    url = paste(url, "&text=", text, sep = "")
  }
  if (lang != "") {
    url = paste(url, "&lang=", lang, sep = "")
  }
  browser()
  d = getURL(url, ssl.verifyhost = 0L, ssl.verifypeer = 0L)
  d = fromJSON(d)
  d$code = NULL
  d
}
```

The error comes from ``d = getURL(url, ssl.verifyhost = 0L, ssl.verifypeer = 0L)`` and it's a function from RCurl which doesn't know how to deal with space.  I simply added ``url = gsub(pattern = " ", replacement = "%20", x = url)```

Therefore the full function is like this :
```
translate = function (api_key, text = "", lang = "") 
{
  url = "https://translate.yandex.net/api/v1.5/tr.json/translate?"
  url = paste(url, "key=", api_key, sep = "")
  if (text != "") {
    url = paste(url, "&text=", text, sep = "")
  }
  if (lang != "") {
    url = paste(url, "&lang=", lang, sep = "")
  }
  url = gsub(pattern = " ", replacement = "%20", x = url)
  d = RCurl::getURL(url, ssl.verifyhost = 0L, ssl.verifypeer = 0L)
  d = jsonlite::fromJSON(d)
  d$code = NULL
  d
}
```

And it works!

**Comment by laresbernardo** [comment]
Same here! Worked you function fix ;) Thanks @l4mun

**Comment by Nikhil5harma** [comment]
Thanks so much @l4mun.
Appreciate your help !!!
